spring:
  application:
    name: Wild-Beyond

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/wild_beyond}
    username: ${DB_USERNAME:wildbeyond}
    password: ${DB_PASSWORD:wildbeyond123}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  file:
    name: E:/Wild-Beyond/app.log
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG

